# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]

# https://www.patreon.com/
patreon: simonwhatley

# https://opencollective.com/
# Replace with a single Open Collective username
open_collective:

# https://ko-fi.com/
# Replace with a single Ko-fi username
ko_fi:

# https://tidelift.com/
# Replace with a single Tidelift platform-name/package-name e.g., npm/babel
tidelift:

# https://crowdfunding.lfx.linuxfoundation.org/
# Replace with a single Community Bridge project-name e.g., cloud-foundry
community_bridge:

# https://en.liberapay.com/
# Replace with a single Liberapay username
liberapay:

# https://issuehunt.io/
# Replace with a single IssueHunt username
issuehunt:

# https://otechie.com/
# Replace with a single Otechie username
otechie:

# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom:
